config/routes.rb
Rails.application.routes.draw do
  resources :employees
  resources :groups
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  root to: "dashboard#index"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :users
  has_many :groups
  validates :name, presence: true, uniqueness: true
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :company
  has_and_belongs_to_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :company
  accepts_nested_attributes_for :company
  has_and_belongs_to_many :groups
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show]

  def index
    @employees = current_user.company.users
  end

  def show 
  end

  def new
    @employee = User.new
    @groups = current_user.company.groups
  end

  def create
    @employee = User.new(user_params)
    @employee.company = current_user.company
    add_groups

    respond_to do |format|
      if @employee.save
        format.html { redirect_to employees_path, notice: 'Employee was successfully added.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def set_employee
      @employee = current_user.company.users.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:email).merge(password: Devise.friendly_token.first(8))
    end

    def add_groups
      params[:user][:groups].each do |group_id|
        if group_id != ''
          @employee.groups << Group.find_by_id(group_id)
        end
      end
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = current_user.company.groups
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)
    @group.company = current_user.company

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = current_user.company.groups.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name)
    end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  layout 'authentication', only: [:new]
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    build_resource({})
    self.resource.company = Company.new
    respond_with self.resource
  end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, company_attributes: [:name]])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  layout 'authentication'
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/employees/index.html.erb
<div class="content__inner">
    <div class="toolbar">
      <nav class="toolbar__nav">
        <%= link_to 'Users', employees_path, class: 'active' %>
        <%= link_to 'Groups', groups_path %>
      </nav>
      <div class="actions">
          <i class="actions__item zmdi zmdi-search" data-ma-action="toolbar-search-open"></i>
          <%= link_to '', new_employee_path, class: 'actions__item zmdi zmdi-plus hidden-xs-down' %>
      </div>
      <div class="toolbar__search">
        <input type="text" placeholder="Search...">
        <i class="toolbar__search__close zmdi zmdi-long-arrow-left" data-ma-action="toolbar-search-close"></i>
      </div>
    </div>

    <div class="contacts row">
        <% @employees.each do |employee| %>
            <div class="col-xl-2 col-lg-3 col-sm-4 col-6">
                <div class="contacts__item">
                    <%= link_to employee_path(employee), class: 'contacts__img' do %>
                      <img src="demo/img/contacts/<%= employee.id %>.jpg" alt="">
                    <% end %>
                    <div class="contacts__info">
                        <strong><%= employee.name %></strong>
                        <small><%= employee.email %></small>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/employees/new.html.erb
<%= simple_form_for @employee, url: employees_path do |f| %>

  <div class="form-inputs">
    <%= f.input :email %>
  </div>

  <div class="form-inputs">
    <%= f.input :groups, collection: @groups, input_html: { multiple: true } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/employees/show.html.erb
<div class="content__inner content__inner--sm">
    <div class="card profile">
        <div class="profile__img">
            <img src="/demo/img/contacts/2.jpg" alt="">

            <a href="" class="zmdi zmdi-camera profile__img__edit"></a>
        </div>

        <div class="profile__info">
            <p>Cras mattis consectetur purus sit amet fermentum. Maecenas sed diam eget risus varius blandit sit amet non magnae tiam porta sem malesuada magna mollis euismod.</p>

            <ul class="icon-list">
                <li><i class="zmdi zmdi-phone"></i> 308-360-8938</li>
                <li><i class="zmdi zmdi-email"></i> malinda@inbound.plus</li>
                <li><i class="zmdi zmdi-twitter"></i> @mallinda-hollaway</li>
            </ul>
        </div>
    </div>

    <div class="toolbar">
        <nav class="toolbar__nav">
            <a class="active" href="profile-about.html">About</a>
            <a href="profile-photos.html">Photos</a>
            <a href="profile-contacts.html">Contacts</a>
        </nav>

        <div class="actions">
            <i class="actions__item zmdi zmdi-search" data-ma-action="toolbar-search-open"></i>
        </div>

        <div class="toolbar__search">
            <input type="text" placeholder="Search...">

            <i class="toolbar__search__close zmdi zmdi-long-arrow-left" data-ma-action="toolbar-search-close"></i>
        </div>
    </div>

    <div class="card">
        <div class="card-body">
            <h4 class="card-body__title mb-4">About Mallinda Hollaway</h4>

            <p>Pellentesque vitae quam quis tellus dignissim faucibus. Suspendisse mattis felis at faucibus lobortis. Sed sit amet tellus dolor. Fusce quis sollicitudin velit. Praesent gravida ullamcorper lectus et tincidunt. Phasellus lectus quam, porta pharetra feugiat in, auctor eget dolor.</p>

            <p>Vestibulum tincidunt imperdiet egestas. In in nunc vitae elit tincidunt tristique id eu justo. Quisque gravida maximus orci, vulputate pharetra mauris commodo at. Mauris eget fermentum ipsum, quis faucibus neque. Fusce eleifend sapien sit amet convallis rhoncus. Proin commodo lacinia lectus, et tempus turpis.</p>

            <br>

            <h4 class="card-body__title mb-4">Contact Information</h4>

            <ul class="icon-list">
                <li><i class="zmdi zmdi-phone"></i>308-360-8938</li>
                <li><i class="zmdi zmdi-email"></i>robertbosborne@inbound.plus</li>
                <li><i class="zmdi zmdi-facebook"></i>robertbosborne</li>
                <li><i class="zmdi zmdi-twitter"></i>@robertbosborne</li>
                <li><i class="zmdi zmdi-pin"></i>5470 Madison Street Severna Park, MD 21146</li>
            </ul>
        </div>
    </div>
</div>

app/views/groups/_form.html.erb
<%= simple_form_for(@group) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<div class="content__inner">
  <div class="toolbar">
      <nav class="toolbar__nav">
        <%= link_to 'Users', employees_path %>
        <%= link_to 'Groups', groups_path, class: 'active' %>
      </nav>
      <div class="actions">
          <i class="actions__item zmdi zmdi-search" data-ma-action="toolbar-search-open"></i>
          <%= link_to '', new_group_path, class: 'actions__item zmdi zmdi-plus hidden-xs-down' %>
      </div>
      <div class="toolbar__search">
        <input type="text" placeholder="Search...">
        <i class="toolbar__search__close zmdi zmdi-long-arrow-left" data-ma-action="toolbar-search-close"></i>
      </div>
  </div>

  <div class="row groups">
    <% @groups.each do |group| %>
      <div class="col-xl-2 col-lg-3 col-sm-4 col-6">
          <div class="groups__item">
              <%= link_to(group) do %>
                <div class="groups__img">
                    <img class="avatar-img" src="/demo/img/contacts/1.jpg" alt="">
                    <img class="avatar-img" src="/demo/img/contacts/2.jpg" alt="">
                    <img class="avatar-img" src="/demo/img/contacts/3.jpg" alt="">
                    <img class="avatar-img" src="/demo/img/contacts/4.jpg" alt="">
                </div>

                <div class="groups__info">
                    <strong><%= group.name %></strong>
                    <small><%= group.users.count %></small>
                </div>
              <% end %>

              <div class="actions">
                  <div class="dropdown actions__item">
                      <i class="zmdi zmdi-more-vert" data-toggle="dropdown"></i>

                      <div class="dropdown-menu dropdown-menu-right">
                          <%= link_to 'Edit', edit_group_path(group), class: 'dropdown-item' %>
                          <%= link_to 'Delete', 
                                      group, 
                                      method: :delete, data: { confirm: 'Are you sure?' },
                                      class: 'dropdown-item' %>
                          <a class="dropdown-item" href="" data-demo-action="delete-listing">Delete</a>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    <% end %>
  </div>
</div>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @group.name %>
</p>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>

app/views/layouts/_alerts.html.erb
<% if notice != nil %>
  <div class="alert alert-info alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <%= notice %>
  </div>
<% end %>
<% if alert != nil %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <%= alert %>
  </div>
<% end %>

app/views/layouts/_browser_warnings.html.erb
<!-- Older IE warning message -->
    <!--[if IE]>
        <div class="ie-warning">
            <h1>Warning!!</h1>
            <p>You are using an outdated version of Internet Explorer, please upgrade to any of the following web browsers to access this website.</p>

            <div class="ie-warning__downloads">
                <a href="http://www.google.com/chrome">
                    <img src="img/browsers/chrome.png" alt="">
                </a>

                <a href="https://www.mozilla.org/en-US/firefox/new">
                    <img src="img/browsers/firefox.png" alt="">
                </a>

                <a href="http://www.opera.com">
                    <img src="img/browsers/opera.png" alt="">
                </a>

                <a href="https://support.apple.com/downloads/safari">
                    <img src="img/browsers/safari.png" alt="">
                </a>

                <a href="https://www.microsoft.com/en-us/windows/microsoft-edge">
                    <img src="img/browsers/edge.png" alt="">
                </a>

                <a href="http://windows.microsoft.com/en-us/internet-explorer/download-ie">
                    <img src="img/browsers/ie.png" alt="">
                </a>
            </div>
            <p>Sorry for the inconvenience!</p>
        </div>
    <![endif]-->

app/views/layouts/_chat_aside.html.erb
<aside class="chat">
    <div class="chat__header">
        <h2 class="chat__title">Chat <small>Currently 20 contacts online</small></h2>

        <div class="chat__search">
            <div class="form-group">
                <input type="text" class="form-control" placeholder="Search...">
                <i class="form-group__bar"></i>
            </div>
        </div>
    </div>

    <div class="scrollbar-inner">
        <div class="listview listview--hover chat__buddies">
            <a class="listview__item chat__available">
                <img src="/demo/img/profile-pics/7.jpg" class="listview__img" alt="">

                <div class="listview__content">
                    <div class="listview__heading">Jeannette Lawson</div>
                    <p>hey, how are you doing.</p>
                </div>
            </a>

            <a class="listview__item chat__available">
                <img src="/demo/img/profile-pics/5.jpg" class="listview__img" alt="">

                <div class="listview__content">
                    <div class="listview__heading">Jeannette Lawson</div>
                    <p>hmm...</p>
                </div>
            </a>

            <a class="listview__item chat__away">
                <img src="/demo/img/profile-pics/3.jpg" class="listview__img" alt="">

                <div class="listview__content">
                    <div class="listview__heading">Jeannette Lawson</div>
                    <p>all good</p>
                </div>
            </a>

            <a class="listview__item">
                <img src="/demo/img/profile-pics/8.jpg" class="listview__img" alt="">

                <div class="listview__content">
                    <div class="listview__heading">Jeannette Lawson</div>
                    <p>morbi leo risus portaac consectetur vestibulum at eros.</p>
                </div>
            </a>

            <a class="listview__item">
                <img src="/demo/img/profile-pics/6.jpg" class="listview__img" alt="">

                <div class="listview__content">
                    <div class="listview__heading">Jeannette Lawson</div>
                    <p>fusce dapibus</p>
                </div>
            </a>

            <a class="listview__item chat__busy">
                <img src="/demo/img/profile-pics/9.jpg" class="listview__img" alt="">

                <div class="listview__content">
                    <div class="listview__heading">Jeannette Lawson</div>
                    <p>cras mattis consectetur purus sit amet fermentum.</p>
                </div>
            </a>
        </div>
    </div>

    <a href="messages.html" class="btn btn--action btn-danger"><i class="zmdi zmdi-plus"></i></a>
</aside>

app/views/layouts/_page_loader.html.erb
<div class="page-loader">
  <div class="page-loader__spinner">
    <svg viewBox="25 25 50 50">
      <circle cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10" />
    </svg>
  </div>
</div>

app/views/layouts/_sidebar.html.erb
<aside class="sidebar">
    <div class="scrollbar-inner">
        <div class="user">
            <div class="user__info" data-toggle="dropdown">
                <img class="user__img" src="/demo/img/profile-pics/8.jpg" alt="">
                <div>
                    <div class="user__name"><%= current_user.name %></div>
                    <div class="user__email"><%= current_user.email %></div>
                </div>
            </div>

            <div class="dropdown-menu">
                <%= link_to 'View Profile', edit_user_registration_path, class: 'dropdown-item' %>
                <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
            </div>
        </div>

        <ul class="navigation">
            <li class="navigation__active"><a href="index.html"><i class="zmdi zmdi-home"></i> Home</a></li>
            <li>
                <%= link_to(employees_path) do %>
                    <i class="zmdi zmdi-male-female"></i> Coworkers
                <% end %>
            </li>
            <li>
                <%= link_to(groups_path) do %>
                    <i class="zmdi zmdi-accounts"></i> Groups
                <% end %>
            </li>
        </ul>
    </div>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RemoteHome</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body data-ma-theme="blue">
    <main class="main">
      <%= render(:partial => "layouts/navbar") %>
      <%= render(:partial => "layouts/sidebar") %>
      <%= render(:partial => "layouts/chat_aside") %>
      <section class="content">
        <%= render(:partial => "layouts/alerts") %>
        <%= yield %>
      </section>
    </main>
    <%= render(:partial => "layouts/browser_warnings") %>
  </body>
</html>

app/views/layouts/authentication.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RemoteHome</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body data-ma-theme="blue">
<!--     <%= render(:partial => "layouts/page_loader") %> -->
    <%= render(:partial => "layouts/alerts") %>
    <%= yield %>
    <%= render(:partial => "layouts/browser_warnings") %>
    </body>
</html>